version: '3.4'

services:
 catalogdb:
    container_name: catalogdb
    restart: always
    volumes:
        - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
        - "27017:27017"
 basketdb:
   container_name: basketdb
   restart: always    
   ports:
      - "6379:6379"

 catalog.api:
    container_name: catalogapi
    environment:
      - "CatalogDatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - catalogdb
    volumes:
     - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
     - ${HOME}/.aspnet/https:/root/.aspnet/https/
    ports:
       - "8000:80"
 basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
    depends_on:
     - basketdb
    ports:
      - "8001:80"

 discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=123qwe!@#QWE;"
      
    depends_on:
      - discountdb
    ports:
      - "8002:80"


 discountdb:
    container_name: discountdb
    environment:
    - POSTGRES_USER=admin
    - POSTGRES_PASSWORD=123qwe!@#QWE
    - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
     - postgres_data:/var/lib/postgresql/data/

 pgadmin:
   container_name: pgadmin
   environment:
     - PGADMIN_DEFAULT_EMAIL=pouya@samie.uk
     - PGADMIN_DEFAULT_PASSWORD=123qwe!@#QWE
   restart: always
   ports:
     - "5050:80"
   volumes:
    - pgadmin_data:/root/.pgadmin

 portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data


 apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

